### ISSUE TITLE
[CI Problem] Flaky test (Ethos-U FVP demo)

### ISSUE THREAD

**Issue by areusch** [apache/tvm#10020]
### Branch/PR Failing

https://github.com/apache/tvm/pull/10017

### Jenkins Link

https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/PR-10017/1/pipeline

### Flakiness

Yes, but I don't have links atm.

cc @mousius @grant-arm

**Comment by Mousius** [comment]
I think this is another stale CI workspace issue, as @grant-arm has been updating the demo to use CMSIS-NN for some ops in https://github.com/apache/tvm/pull/9979.

Because TVM doesn't use a clean workspace in CI, it must be keeping the demo `build` folder with the CMSIS-NN files generated into it from that PR and thus some machines have them - we'll put a clean step into the demo as a workaround.

**Comment by junrushao1994** [comment]
Looks like it's a duplicated issue as #10029

**Comment by driazati** [comment]
workspaces are usually cleaned before each run now and we haven't seen this lately afaik, so closing
