### ISSUE TITLE
CI monitoring rotation schedule

### ISSUE THREAD

**Issue by driazati** [apache/tvm#11462]
See [the CI Monitoring Runbook](https://github.com/apache/tvm/wiki/CI-Monitoring-Runbook) for context.

This schedule tracks the CI monitoring rotation. If you would like to join, please comment on this issue or, if you are a committer, edit this issue directly.

| Week (MM/DD) | On-call          |
|-----------|------------------|
| 8/1 - 8/5 | @driazati  |
| 8/8 - 8/12 | @gigiblender  |
| 8/15 - 8/19 | @shingjan  |
| 8/22 - 8/26 | @cconvey  |
| 8/29 - 9/2 | @sunggg  |
| 9/5 - 9/9 | @driazati  |
| 9/12 - 9/16 |  @nverke   |
| 9/19 - 9/23 |  ---   |
| 9/26 - 9/30 |  ---   |
| 10/3 - 10/7 |  ---   |

**Comment by areusch** [comment]
Summary from my week: things were fairly quiet, mainly some flaky tests.

- [[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3414/pipeline)](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3414/pipeline) on c1b22ee - flaky test, filed https://github.com/apache/tvm/issues/11527
- [[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3415/pipeline)](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3415/pipeline) on ac5d781 - continued flaky paddlepaddle test, updated https://github.com/apache/tvm/issues/9976. better diagnostic submitted today.
- [[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3411/pipeline)](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3411/pipeline) on bc14f26 - network flake, filed https://github.com/apache/tvm/issues/11514
- [[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3444/tests)](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3444/tests) on 2ae2088 - assert_allclose 2/10000 mismatched (0.02%), filed https://github.com/apache/tvm/issues/11568
-

**Comment by hpanda-naut** [comment]
@areusch @driazati I can take next week

**Comment by gigiblender** [comment]
Happy to sign up for 6/27-7/1 if someone could edit the issue for me :)

**Comment by nverke** [comment]
Week of 6/20 - 6/27: 
- [Details](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3599/pipeline) on [bc75487](https://github.com/apache/tvm/commit/bc75487032aee5d0fa2bb1d673f9dcd8c7e43810) #11830
- [Details](https://ci.tlcpack.ai/job/tvm/job/main/3602/display/redirect) on [b63801c](https://github.com/apache/tvm/commit/b63801c4cd79508eec4d0d210cf62764dfacf6e1) #11811
- [Details](https://ci.tlcpack.ai/job/tvm/job/main/3603/display/redirect) on [a363a04](https://github.com/apache/tvm/commit/a363a04720ee78fa50c569cd96da6a0de1281174) #11811
- [Details](https://ci.tlcpack.ai/job/tvm/job/main/3604/display/redirect) on [7b0f791](https://github.com/apache/tvm/commit/7b0f791e120eedcebfb403d8ac44e289a7065651) #11811
- [Details](https://ci.tlcpack.ai/job/tvm/job/main/3605/display/redirect) on [a5366a7](https://github.com/apache/tvm/commit/a5366a7d1968e6f00a9fea10719a8deccfb78385) #11811 
- [Details](https://ci.tlcpack.ai/job/tvm/job/main/3606/display/redirect) on [32d16eb](https://github.com/apache/tvm/commit/32d16eb358c51b1c142c400a973f516d607a21b4) #11917
- [Details](https://ci.tlcpack.ai/job/tvm/job/main/3608/display/redirect) on [98fb955](https://github.com/apache/tvm/commit/98fb955a5153e3d4f66fa3b9403e515da31c54b6) #11840 
- [Details](https://ci.tlcpack.ai/job/tvm/job/main/3609/display/redirect) on [6ed3ab3](https://github.com/apache/tvm/commit/6ed3ab3e33f8eafa4acaf53b7a671831de7587e9) #11840
- [Details](https://ci.tlcpack.ai/job/tvm/job/main/3610/display/redirect) on [1e0e954](https://github.com/apache/tvm/commit/1e0e9548a6875241267481a4223b4dbf29fa1641) (Fixed not sure what the issue was)
- [Details](https://ci.tlcpack.ai/job/tvm/job/main/3612/display/redirect) on [51b0d8c](https://github.com/apache/tvm/commit/51b0d8c44a80f7f01ae2a0480db107633d7dbc45) #11580 
- [Details](https://ci.tlcpack.ai/job/tvm/job/main/3625/display/redirect) on [410e836](https://github.com/apache/tvm/commit/410e836025d2c0f6f193cbf523dc7c1921093b17) #11580 
- [Details](https://ci.tlcpack.ai/job/tvm/job/main/3631/display/redirect) on [12e8744](https://github.com/apache/tvm/commit/12e8744cd1e6f5e4864f94f8b089f4cb7e2e5b59) #11918
- [Details](https://ci.tlcpack.ai/job/tvm/job/main/3640/display/redirect) on [5e81067](https://github.com/apache/tvm/commit/5e810678186a0cfddcd295869c91a8a3b16995b8) #11580 
- [Details](https://ci.tlcpack.ai/job/tvm/job/main/3642/display/redirect) on [4cb18b4](https://github.com/apache/tvm/commit/4cb18b43d1aa6402b76ddf18f7273f56fd3de0af) #11919
- [Details](https://ci.tlcpack.ai/job/tvm/job/main/3650/display/redirect) on [aa66e9f](https://github.com/apache/tvm/commit/aa66e9fd84192f321efb1fac90c6086a6f7b5651) #11918
- [Details](https://ci.tlcpack.ai/job/tvm/job/main/3662/display/redirect) on [600a201](https://github.com/apache/tvm/commit/600a2017a4da6ace588b30360bee35b5a3cd6c73) #11840 
- [Details](https://ci.tlcpack.ai/job/tvm/job/main/3663/display/redirect) on [98bf40f](https://github.com/apache/tvm/commit/98bf40fc0afb0e40efa8b7a6cf2f664e17a89db7) #11920

**Comment by gigiblender** [comment]
27/06/2022
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3668/pipeline) on 1115fd9bc261619ffa0539746ae0aebc46232dc6 [aborted due to CI disk space issue](https://github.com/apache/tvm/issues/11840)

28/06/2022
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3690/pipeline) on 6c8a3530998d46182fe0887a24739d21961a056d https://github.com/apache/tvm/issues/11580
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3691/pipeline) on 688b0825e2ea9ffedafaa83d4027701a4a8a67d1 https://github.com/apache/tvm/issues/11580

29/06/2022
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3695/pipeline) on a17bfc05cc127dd8d3922d7b79b7ff4754893d49 https://github.com/apache/tvm/issues/11964

30/06/2022
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3707/pipeline) on 41c94b27ef5f10ad70af211dd25c4837dad53f64 https://github.com/apache/tvm/issues/11967
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3709/) on 898946fec60898b8fa753d6f0cdf8ebc86c9827a https://github.com/apache/tvm/issues/11567
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3710/pipeline) on 558ba99c7cad6fa5f01cfdb2bd6bdd2cec6087db https://github.com/apache/tvm/issues/12004 and [flaky due to network](https://github.com/apache/tvm/issues/11514)
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3712/) on e7851ed763cd9e7e64c1e298908297d3f4ba93c7 https://github.com/apache/tvm/issues/11967
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3713/pipeline) on 80a0c6c53dc7e3aca2bc52755fabbad76cbac35a https://github.com/apache/tvm/issues/11967
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3714/pipeline) on 915c23b61b34604b19217759f320c84d3aa60605 https://github.com/apache/tvm/issues/11967
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3717/pipeline) on c0f4bf72b6ee30648ef78ce865afc733c95fe98c https://github.com/apache/tvm/issues/11967

01/07/2022
[jenkis](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3726/pipeline) on ec39199edb72dfe93747249d6a060c1832a8e38f https://github.com/apache/tvm/issues/11580
[jenkis](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3727/pipeline) on 395e91ff54543864a90240d18c8efd8c277c758b https://github.com/apache/tvm/issues/11580
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3729/pipeline) on 9e14509cabf9e6ba674d819d36b5d29f97f3dc2f https://github.com/apache/tvm/issues/11568
[jenkis](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3732/pipeline) on 50cd4d635cb0947e90d5d8ecdd94baeabf57ab31 https://github.com/apache/tvm/issues/11568

**Comment by areusch** [comment]
- [[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3753/pipeline/)](https://ci.tlcpack.ai/blue/organizations/[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3755/pipeline)/tvm/detail/main/3753/pipeline/) on cfe8318 - failed to docker pull from DockerHub
- [[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3762/pipeline)](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3755/pipeline) on 9f4bf38 - failed to docker pull from DockerHub
- [jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3762/pipeline) on 99d42b2 - test_qlinearadd tolerance, filed [https://github.com/apache/tvm/issues/12062](https://github.com/apache/tvm/issues/12062)
- [[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3767/pipeline)](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3767/pipeline) on f769f4e - Skipped has no len, added to [https://github.com/apache/tvm/issues/11749](https://github.com/apache/tvm/issues/11749)
- [[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3769/pipeline)](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3769/pipeline) on a81e69a - http flake

**Comment by sunggg** [comment]
07/11/2022: No CI failure

**Comment by yongwww** [comment]
Summary for 7/25/22 - 7/29/22: 

[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3900/pipeline/) on https://github.com/apache/tvm/commit/eada707a7027bec47cf003916d349893a9249e4d - failure on android-rpc build


[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3900/pipeline/) on https://github.com/apache/tvm/commit/eada707a7027bec47cf003916d349893a9249e4d - failure on android-rpc build


[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3900/pipeline/) on https://github.com/apache/tvm/commit/eada707a7027bec47cf003916d349893a9249e4d - failure on android-rpc build

**Comment by driazati** [comment]
Summary for 2022-07-06 to 2022-08-06

|Run|Commit|Mitigation|
|--|--|--|
|[tvm-ci/branch](https://ci.tlcpack.ai/job/tvm/job/main/3983/display/redirect)|1f97f1fbd55ff223dc73dbe62ae1c9b7aa16337a from #11809|Timeout fixed by #12334|
|[tvm-ci/branch](https://ci.tlcpack.ai/job/tvm/job/main/3976/display/redirect)|485bfaf1ea9d7afaf7fa6cb3e03415364ffc4412 from #12306|Fixed by #12325|
|[tvm-ci/branch](https://ci.tlcpack.ai/job/tvm/job/main/3973/display/redirect)|4158738574b7187eb6c9d4f8c473e3c707e268a2 from #12301|Flaky test, filed #12311 and opened #12312 to improve reporting|
|[tvm-ci/branch](https://ci.tlcpack.ai/job/tvm/job/main/3951/display/redirect)|2bfd52f8855eccb0515bb517cfdbc242029b4001 from #12278|Fixed by #12282|
|[tvm-ci/branch](https://ci.tlcpack.ai/job/tvm/job/main/3929/display/redirect)|12502cc835157ed93e2ccba855a2b3cdfd6d1331 from #12251|Fixed by #12268|
|[tvm-ci/branch](https://ci.tlcpack.ai/job/tvm/job/main/3922/display/redirect)|a231a1d724283545c16221fc1316dd77cfa840b6 from #12245|Added retries to fix: #12306|
|[tvm-ci/branch](https://ci.tlcpack.ai/job/tvm/job/main/3913/display/redirect)|fb87c21bf8d0fa5edec96a054a57a6d37c11289f from #12234|Fixed by #12306|
|[tvm-ci/branch](https://ci.tlcpack.ai/job/tvm/job/main/3912/display/redirect)|dff5c975a082e6f15b556914a029541b63ff1280 from #11037|Fixed by #12306|
|[tvm-ci/branch](https://ci.tlcpack.ai/job/tvm/job/main/3911/display/redirect)|db4380cf41757e19c56c62ae3bf3a441c44de521 from #12230|Fixed by #12268|


<sub>Generated by https://gist.github.com/driazati/80cd48e86c6548cd90a6b39be010b921</sub>

**Comment by gigiblender** [comment]
Summary for 2022-08-07 - 2022-08-14:
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3986/) on fc411dc6fad14909ed17ce8c39d621d4587441bc - Failure due to timeout in Cortex-M shards. Fixed in #12334.
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3987/) on 9b860095532d2a01525a449fac2bdfc0813bf4cc - Failure due to timeout in Cortex-M shards. Fixed in #12334.
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4028/) on 8e133b1990eefda82c86b4f5e30191d720effcc4 - Sent interrupt signal to the CI.
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3992/) on 7f800e41de097c333ff5790feb1a8c42575b0fe1 - Fixed by #12341.
[CI MacOS](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/3992/https://github.com/apache/tvm/runs/7751823895?check_suite_focus=true) on 52d6b59a39f503fe382b4d7cbac4b02f9e44aae0 - Filed #12449.
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4012/) on 22102063dccf42c29f9d43ee5684026ba67a3386 - Failure due to linting the Jenkinsfile. Fixed by #12360.
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4013/) on 5d72bc1a20461925e3e4f7f47907ae9173bb183b - Failure due to linting the Jenkinsfile. Fixed by #12360.
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4014/) on 7f100158a551ae94db5d401f71479ba341adc7d5 - Failure due to linting the Jenkinsfile. Fixed by #12360.
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4023/) on 52152e0be641c80c0dbb1e36ab3654efbd27661f - Failure due to linting the Jenkinsfile. Fixed by #12387.
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4024/) on 48354ded387b553b994caedade63ebb08b3ebd30 - Failure due to linting the Jenkinsfile. Fixed by #12387.
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4030/) on 5deb95a9472002c9fa36a150f9e348f4276d63c5 - Deploy docs failed to `git push` in the CI.
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4040/) on c3c7c4ccc3e3ebb7cc4dbb55e8dde579ac52c949 - Failed due to flaky test. #12451.
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4043/) on 3eb673478bc444daf24ee8d6308a42a71c81b74f - Failed due to flaky test. #12451.
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4046/) on 1737308397e0f105c387d9ee6c466584aded1d7d - Linting failed with exit code 4.

**Comment by shingjan** [comment]
Summary for 2022-08-15 to 2022-08-17

|Run|Commit|Mitigation|
|--|--|--|
|[tvm-ci/branch](https://ci.tlcpack.ai/job/tvm/job/main/4073/display/redirect)|1ba17fe48b254a287458834041bd4aaf7d9f49b5 from #12401|<fill this out>|
|[tvm-ci/branch](https://ci.tlcpack.ai/job/tvm/job/main/4072/display/redirect)|bd562313250ce6a1bcc90eb7e94f64bc10563104 from #12443|<fill this out>|


<sub>Generated by https://gist.github.com/driazati/80cd48e86c6548cd90a6b39be010b921</sub>

**Comment by cconvey** [comment]
Summary for 2022-08-22 to 2022-08-29

|Run|Commit|Mitigation|
|--|--|--|
|[tvm-ci/branch](https://ci.tlcpack.ai/job/tvm/job/main/4158/display/redirect)|1afd0593956066635ee49297b731726c9218c91c from #12340|Checks API failure (https://github.com/apache/tvm/issues/12602)|
|[tvm-ci/branch](https://ci.tlcpack.ai/job/tvm/job/main/4149/display/redirect)|90b2f0d36996be10d71f0c923f588c6dfa0e8546 from #12557|maven problem (https://github.com/apache/tvm/issues/12601)|
|[CI / Android](https://github.com/apache/tvm/runs/7983481668?check_suite_focus=true)|8174d082e8168db9ad63826c9d68aee8c76c7090|android_rpc build failure (https://github.com/apache/tvm/issues/12599)|
|[tvm-ci/branch](https://ci.tlcpack.ai/job/tvm/job/main/4144/display/redirect)|13ebbfb37f8cec1da71d88fbcbecdd4ad4d24dcc from #12562|Deploy docs failed to git push in the CI (https://github.com/apache/tvm/issues/12600)|
|[tvm-ci/branch](https://ci.tlcpack.ai/job/tvm/job/main/4135/display/redirect)|52779f1273b05d53d8213e23e70d9b0ac82fd0b9 from #12353|ethos-u failures (https://github.com/apache/tvm/issues/12511)|
|[tvm-ci/branch](https://ci.tlcpack.ai/job/tvm/job/main/4133/display/redirect)|3983a472c6f3ad4ad9604ceeffdf80cce01d166b from #12543|ethos-u failures (https://github.com/apache/tvm/issues/12511)|
|[tvm-ci/branch](https://ci.tlcpack.ai/job/tvm/job/main/4132/display/redirect)|d26bf809e4c3c8d6576d4e436475997eb12deb3e from #12541|ethos-u failures (https://github.com/apache/tvm/issues/12511)|
|[tvm-ci/branch](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4188/pipeline)|534412896e6d39ee4f830d63370d02e8e5f09050 from PR https://github.com/apache/tvm/pull/12623|internal pytest failure during ethos-u testing (https://github.com/apache/tvm/issues/12634)|

<sub>Generated by https://gist.github.com/driazati/80cd48e86c6548cd90a6b39be010b921</sub>

**Comment by sunggg** [comment]
Summary for 8/29 - 9/2

[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4193/pipeline) on https://github.com/apache/tvm/commit/0de22196db5f818a6937f026db43785935b9e731 - Unable to find image 'tlcpack/ci-lint:20220810-060142-fae79bbc3' locally
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4194/pipeline) on https://github.com/apache/tvm/commit/0de22196db5f818a6937f026db43785935b9e731 - Segmentation fault (core dumped)
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4196/pipeline) on https://github.com/apache/tvm/commit/74988d36bd578b791bbdcea383d343d62029e9cf - Failed unit tests
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4199/pipeline) on https://github.com/apache/tvm/commit/58ee935a53893bfd47b9cd7ea4738ecec8d7181e - Failed unit tests
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4211/pipeline) on https://github.com/apache/tvm/commit/a399e6ce9759cd524fcb8f804749baa426096e4b - Failed unit tests
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4213/pipeline) on https://github.com/apache/tvm/commit/aa6c7123d0a2cdd93256c6a4576ff029008fd375- segfault in `tests/scripts/setup-pytest-env.sh`
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4220/pipeline) on https://github.com/apache/tvm/commit/50dad0d9a3c85f7692025b5330ceb902e264bb92 - failed to push due to merge conflcit
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4221/pipeline) on https://github.com/apache/tvm/commit/eecb7fd494052ca941f3d123daa2e887f14b7e75 - segfault in `tests/scripts/setup-pytest-env.sh`
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4224/pipeline) on https://github.com/apache/tvm/commit/b2d660006446f720f0c9488f96d28387cbd0d294 - ERROR `tests/python/frontend/darknet/test_forward.py` - urllib.error.HTTPError
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4225/pipeline) on https://github.com/apache/tvm/commit/bb56f2a972606b33e5479d1e18d4c4f13751eeed - http error 502 on ``tests/python/frontend/tflite/test_forward.py`
[jenkins](https://ci.tlcpack.ai/blue/organizations/jenkins/tvm/detail/main/4227/pipeline) on https://github.com/apache/tvm/commit/0549a08f4de40a5a0db277cfe1ae00ab22fc9107 - urllib.error.HTTPError: HTTP Error 503: Service Unavailable
