### ISSUE TITLE
[Bug] `tanh` outputs `1.` for `nan` input at optimization level 4

### ISSUE THREAD

**Issue by wzh99** [apache/tvm#11696]
### Expected behavior

The output of `tanh` for `nan` input at optimization level 4 should be consistent with lower optimization levels. 

### Actual behavior

`tanh` outputs `1.` at optimization level 4, and `nan` at lower levels. 

```
opt_level=0 [nan]
opt_level=1 [nan]
opt_level=2 [nan]
opt_level=3 [nan]
opt_level=4 [1.]
```

### Environment

macOS 12.4. Compiled using Clang 13.1.6 with LLVM support. TVM commit [`8341e33`](https://github.com/apache/tvm/commit/8341e33d05868b7bb8496c913679b7951836f3b9).

### Steps to reproduce

```python
import numpy as np
from tvm import relay, transform, cpu, IRModule
from tvm.contrib.graph_executor import GraphModule

x = relay.var('x', shape=(1,), dtype='float32')
y = relay.tanh(x)
mod = IRModule.from_expr(y)
for level in range(5):
    with transform.PassContext(opt_level=level):
        lib = relay.build(mod, target='llvm')
        gmod = GraphModule(lib['default'](cpu()))
        gmod.run(x=np.array([np.nan]))
        print(f'opt_level={level}', gmod.get_output(0))
```

### Possible cause

https://github.com/apache/tvm/blob/8341e33d05868b7bb8496c913679b7951836f3b9/src/relay/transforms/fast_math.cc#L48-L49

`tanh` is replaced by `fast_tanh` in `FastMath` pass at optimization level 4. 

https://github.com/apache/tvm/blob/8341e33d05868b7bb8496c913679b7951836f3b9/include/tvm/topi/elemwise.h#L84

If the data type of `fast_tanh` is `float32`, TOPI uses a fast float implementation of `tanh`. In this line, the input is clamped to [-9, 9]. `nan` may be incorrectly "clamped" to 9 here. Then the output of this implementation will be 1.

**Comment by ganler** [comment]
Thanks for the bug report! 

However, I think using invalid numerics (i.e., "nan" or "inf") as inputs should be considered undefined behavior. "Fixing" may require extra checking overhead. According to my experience, there will be lots of such "bugs" in fast math. For example, many PyTorch [fast math](https://github.com/pytorch/pytorch/blob/429a80dded856cd06bd12bd9118efce5ac13dba3/torch/csrc/jit/tensorexpr/expr.cpp#L150) impl does not consider invalid inputs. I guess that is because generally, fast math targets best performance with acceptable approximation over valid domains.

Personally, I will avoid fuzzing bugs triggered by NaN/Inf inputs as they easily lead to false positives. For example, IEEE 754 even "bans" trichotomy for NaN so that `nan == nan` returns `False` in PyTorch/Numpy, etc. (You can email me if you are interested in more false-positive stories. :-)

Let me also cc @junrushao1994 for more professional opinions.

**Comment by wzh99** [comment]
@ganler Thanks for your reply. Your explanation is reasonable. I agree that fast math implementation does not always need to consider all kinds of invalid inputs.

Actually I does not intentionally feed `nan` to `tanh` to discover this inconsistency. Instead, I generated a computation graph and feed it with valid inputs. The `nan`s appear in intermediate results. The test case shown above is a reduced version of what is generated by my fuzzer. I think that the `nan`s in intermediate values are not completely avoidable for arbitrary tensor programs. 

Just now I figure out a quick fix of this inconsistency without introducing overhead. I replace the clamping code in [tvm/include/tvm/topi/elemwise.h](https://github.com/apache/tvm/blob/8341e33d05868b7bb8496c913679b7951836f3b9/include/tvm/topi/elemwise.h) with the following code:
```c++
auto x = maximum(make_const(in->dtype, -9.0), minimum(make_const(in->dtype, 9.0), in));
```
And the result at optimization level 4 is consistent with lower levels:
```
opt_level=0 [nan]
opt_level=1 [nan]
opt_level=2 [nan]
opt_level=3 [nan]
opt_level=4 [nan]
```
I just exchange the two arguments in `maximum` and `minimum`. The reason why this works is probably that `minimum(x, 9)` is implemented by `x <= 9 ? x : 9`. If `x` is `nan`, its comparison with any floating point is false. In this case `x <= 9 ? x : 9` evaluates to 9, which is a wrong clamp. In contrast, `9 <= x ? 9 : x` evaluates to `nan` and `x` is not clamped to a wrong value.

**Comment by cery999** [comment]
https://github.com/apache/tvm/pull/12702
