### ISSUE TITLE
[Bug]DNNL Codegen Compile failed after PR 11642

### ISSUE THREAD

**Issue by huajsj** [apache/tvm#11824]
### Expected behavior

Append "set(USE_DNNL ON)" in config.cmake after install DNNL, the build should done successfully.

### Actual behavior

There is a compile error  "in function `dnnl::primitive_attr::get_post_ops().. undefined reference to `dnnl_post_ops_clone".

### Environment
TVM after patch 11642

### Steps to reproduce

In last tvm or any version after 11642, enable USE_DNNL, compile would found the error "undefined reference to `dnnl_post_ops_clone".

**Comment by huajsj** [comment]
@apeskov

**Comment by apeskov** [comment]
@huajsj Some additional information. At this moment TVM cmake integration of DNNL targets is not ideal. It search library via path provided by "USE_DNNL" variable. But headers used from system header search paths. So if you have dnnl headers inside of "/usr/local" folder it may be used instead of real DNNL package.

**Comment by huajsj** [comment]
@apeskov , thanks for the kindly follow up, yes that is my environment issue and just trigger by the new patch, after remove the old libdnnl, now the build get success.
