### ISSUE TITLE
[Bug] cpp_deploy demo cannot find PackedFunc

### ISSUE THREAD

**Issue by areusch** [apache/tvm#12022]
See https://discuss.tvm.apache.org/t/discuss-cpp-deploy-did-not-work-in-system-module-mode/12066/4

We should address this before releasing 0.9.

**Comment by driazati** [comment]
This is also broken even going back to `v0.8`, from what I can see the symbols are present in the binary but they're `GetSymbol_` isn't able to find them when the library is loaded in as a system module. There is probably some bug on the codegen side since there aren't even any symbols registered on the module when it's loaded. 

Given it's been broken for so long and I can't find an easy fix I think we should skip this and not make it release blocking

**Comment by areusch** [comment]
cc @hpanda-naut can you triage this?
