### ISSUE TITLE
[Bug] Installation tutorial page shows unexpected blank code block.

### ISSUE THREAD

**Issue by ganler** [apache/tvm#12343]
The [installation](https://tvm.apache.org/docs/tutorial/install.html#sphx-glr-download-tutorial-install-py) page shows unexpected blank code block.

![image](https://user-images.githubusercontent.com/38074777/183534772-8c6d9683-dc73-47b3-bb14-29c098cf2189.png)

cc: @driazati

**Comment by driazati** [comment]
I think this is coming from the `sphinx_gallery_*_ignore` tags, @guberti any idea why they'd show up as a blank code block when there's no other code in that block? This is probably fixable with a patch to sphinx-gallery or we could do the hacky thing and clean these up in JavaScript from `tlcpack-sphinx-addon`

**Comment by guberti** [comment]
This is expected behavior from `sphinx-gallery`. The code that generates the empty block is:

```python
# sphinx_gallery_start_ignore
from tvm import testing

testing.utils.install_request_hook(depth=3)
# sphinx_gallery_end_ignore
```
`sphinx-gallery` correctly removes everything between the `*_ignore` tags (leaving an empty code block) and then renders the empty code block as intended.

The easiest solution is to just remove that code. It was added by @driazati's https://github.com/apache/tvm/pull/11839 and is used to redirect URLS to S3 - since we don't have any other code in this tutorial, I think we can remove it without issue (though @driazati should confirm).
