### ISSUE TITLE
[ci] `gpu_other_build.sh` isn't running

### ISSUE THREAD

**Issue by driazati** [apache/tvm#12777]
See discussion in #12644 for context, this test was being silently skipped before and has broken in the meantime. We should fix it and re-enable it

cc @Mousius @areusch @gigiblender

**Comment by alter-xp** [comment]
hi @driazati @areusch @Mousius @gigiblender 
The function `camke_build` does not use the passed in parameter `path` in `ci/jenkins/Build.groovy.j2,` which causes `tests/scripts/task_build.py` to use `build` as the compilation directory by default. So that `task_config_build_gpu.sh` and `task_config_build_gpu_other` is actually built in the same directory, not in the two directories written in the code (build and build2). Does anyone have any suggestions here？
Should we need to keep them compiled in the same directory? Or separate them?

**Comment by areusch** [comment]
@driazati could you have a look here?

**Comment by driazati** [comment]
afaik the second build is just to test that the build is successful, so after we stash the first build we can delete it and run the second in the same folder, I think we just need to make sure we're clearing the cmake config in between.
