### ISSUE TITLE
[ci] Split up Jenkins into platform-specific jobs

### ISSUE THREAD

**Issue by driazati** [apache/tvm#13337]
Right now all CI (excluding GitHub Actions, which this doesn't address at all) goes through 1 indirection to get any useful information outside of a basic pass/fail, the `tvm-ci/pr-head` job here:

![image](https://user-images.githubusercontent.com/9407960/200953953-ff53b588-0001-4115-8226-16112a9a20f3.png)

The `tvm-ci/pr-head` job then mixes all the tests together, which with sharding means dozens of tests in a long vertical column where it's hard to find exactly what failed. https://github.com/driazati/tvm/pull/38 shows an alternative where each platform (cpu, gpu, arm, etc) has its own job that reports from Jenkins to GitHub independently. To implement this, (1) Jenkins needs to be configured with job definitions for each of these platforms and (2) the `Jenkinsfile` in apache/tvm needs to be broken up

- [x] https://github.com/apache/tvm/pull/13300 splits up the Jenkinsfile into multiple ones per platform, which each of the jobs from (1) are set up to read. This doesn't do anything on its own.
- [x] for (1) that happens in https://github.com/tlc-pack/ci with the jenkins jobs here: https://github.com/tlc-pack/ci/blob/main/jenkins/jenkins-jobs/prod/tvm.yaml. https://github.com/tlc-pack/ci/pull/58 has the changes to move them over from my test repo to the main repo. Once merged this will start reporting the new statuses to GitHub
- [x] Once the previous step is working we can merge https://github.com/apache/tvm/pull/13316 which will make the new statuses required and get rid of the old `tvm-ci/pr-head` requirement.
- [x] Another PR in tlc-pack/ci to remove the `tvm-ci/pr-head` will stop it reporting to GitHub: https://github.com/tlc-pack/ci/commit/20bdc5961fc23d274ac10959379776f6ca267563

Follow up fixes:
- [x] Make tvm-bot rerun aware of the new jobs: #13571
- [ ] Cancel the remaining jobs when any fails (or if just lint fails)
- [ ] Re-balance shards (e.g. for hexagon / cortexm)
- [x] Fix the docs deploy: https://ci.tlcpack.ai/blue/organizations/jenkins/tvm-gpu/detail/main/3/ #13570

This will remove the `Jenkinsfile` at the top level, so Docker image updates would happen now in the `ci/jenkins/data.py` file which has the source data for the Jenkinsfile templates.

cc @Mousius @areusch @gigiblender @leandron

**Comment by driazati** [comment]
This is done now

**Comment by quic-sanirudh** [comment]
@driazati I know this question is probably quite late, but I see that in many PRs, when CI lint fails, the other jobs keep running. I see that there was a task above to fail other jobs when one fails (`Cancel the remaining jobs when any fails (or if just lint fails)`). 

I wonder if this is possible to be enabled now, as I see PRs that have one job failed, but others are still running, and they take up resources causing many other PRs to be waiting (especially for GPU resources).

Would it be possible to kill the other jobs when one fails, or could we enable that at least for lint failures? Could there be other issues because of doing something like this?
