### ISSUE TITLE
[Bug] Which tvm version currently supports rocm？

### ISSUE THREAD

**Issue by wangzy0327** [apache/tvm#13691]
### Expected behavior

Execute tvm code on rocm platform

### Actual behavior

What actually happened

### Environment

tvm 0.10
ubuntu 20.04

### Steps to reproduce

Preferably a minimal script to cause the issue to occur.

### Triage

There is no specified version of rocm is not in the document

* needs-triage

**Comment by wangzy0327** [comment]
I have tried to execute tvm code in rocm 5.2 platform but it not worked which print no correct result. Can you help me?  @tqchen

**Comment by masahi** [comment]
For rocm 5, we need the change to `contrib/rocm.py` in this commit https://github.com/masahi/tvm/commit/26d2701b7823ab4d93b8d980bc8689e9c03b2ee1

Unfortunately the rocm backend is not actively maintained due to fewer interests from users and developers. So our support for rocm is only best-effort basis.
