### ISSUE TITLE
[Bug] undeclared identifier 'RTLD_DI_LOAD_ADDR' while compiling for Hexagon

### ISSUE THREAD

**Issue by aryamazaheri** [apache/tvm#14827]
While compiling TVM for Hexagon backend, I get the following error:
```
/home/osboxes/tvm/src/runtime/dso_library.cc:129:32: error: use of undeclared identifier 'RTLD_DI_LOAD_ADDR'
  int rc = dlinfo(lib_handle_, RTLD_DI_LOAD_ADDR, &p);
```

### Environment

OS: Ubuntu 18.04
TVM: 0.13
Hexagon SDK: 5.3.0.0

### Steps to reproduce

```
HEXAGON_SDK_ROOT=$HOME/Hexagon/5.3.0.0; \
DEFAULT_HEXAGON_TOOLS_ROOT=$HEXAGON_SDK_ROOT/tools/HEXAGON_Tools/8.6.06; \
CC=$DEFAULT_HEXAGON_TOOLS_ROOT/Tools/bin/hexagon-clang; \
CXX=$DEFAULT_HEXAGON_TOOLS_ROOT/Tools/bin/hexagon-clang++;\
CXXFLAGS='-stdlib=libc++ -I${HEXAGON_SDK_ROOT}/rtos/qu^C/computev69/include/posix -I${HEXAGON_SDK_ROOT}/rtos/qurt/computev69/include/qurt'; \
cmake .. -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_VERSION=1 -DCMAKE_C_COMPILER=$DEFAULT_HEXAGON_TOOLS_ROOT/Tools/bin/hexagon-clang -DCMAKE_CXX_COMPILER=$DEFAULT_HEXAGON_TOOLS_ROOT/Tools/bin/hexagon-clang++ -DUSE_RPC=OFF -DUSE_LLVM=OFF
```

### Triage
* vert:hexagon

**Comment by masahi** [comment]
cc @kparzysz-quic

**Comment by abhikran-quic** [comment]
Hi @aryamazaheri ,

I'm trying to check this error and unable to reproduce the problem you've mentioned. 

Request you to please help in sharing insights on the following questions:

1. The command shared by you gives me a different error
```
tvm/src/ir/diagnostic.cc:27:
tvm/3rdparty/rang/include/rang.hpp:11:2: error: Unknown Platform
#error Unknown Platform
 ^
tvm/3rdparty/rang/include/rang.hpp:163:16: error: use of undeclared identifier 'result'
        return result;
               ^
2 errors generated.
```
Not sure if you have seen the same error and have a fix for this ?

2. Are you trying to build TVM runtime for hexagon ?  Or do you want to build TVM so that it can generate code for hexagon backend ?

**Comment by aryamazaheri** [comment]
Hi @abhikran-quic ,
1. I never faced with this problem. Could it be because of `-DCMAKE_SYSTEM_NAME=Linux` in the cmake command?
2. I am trying to build the runtime for hexagon. I have a compute board with Qualcomm SoC and I need to cross compile TVM runtime with hexagon support so that I can run TVM on it.

**Comment by abhikran-quic** [comment]
Thanks @aryamazaheri for sharing the details.

1. The problem went away after removing `-DCMAKE_SYSTEM_NAME=Linux` flag and I was able to reproduce the issue.
2. The issue is seen because a different version of `dlfcn.h` is being picked up while compilation. Ideally it should be picked up from `$HEXAGON_SDK_ROOT/ipc/fastrpc/rtld/ship/inc` which contains `RTLD_DI_LOAD_ADDR` definition. Could you please try with the below mentioned command?
```
HEXAGON_SDK_ROOT=$HOME/Hexagon/5.3.0.0; \
DEFAULT_HEXAGON_TOOLS_ROOT=$HEXAGON_SDK_ROOT/tools/HEXAGON_Tools/8.6.06; \
CC=$DEFAULT_HEXAGON_TOOLS_ROOT/Tools/bin/hexagon-clang; \
CXX=$DEFAULT_HEXAGON_TOOLS_ROOT/Tools/bin/hexagon-clang++;\
cmake .. \
	-DCMAKE_SYSTEM_VERSION=1 \
	-DCMAKE_C_COMPILER=$DEFAULT_HEXAGON_TOOLS_ROOT/Tools/bin/hexagon-clang \
	-DCMAKE_CXX_COMPILER=$DEFAULT_HEXAGON_TOOLS_ROOT/Tools/bin/hexagon-clang++ \
	-DUSE_RPC=OFF -DUSE_LIBBACKTRACE=OFF -DUSE_LLVM=OFF \
	-DCMAKE_CXX_FLAGS="-isystem $HEXAGON_SDK_ROOT/incs \
		-isystem $HEXAGON_SDK_ROOT/incs/stddef \
		-isystem $HEXAGON_SDK_ROOT/rtos/qurt/computev68/include/posix \
		-isystem $HEXAGON_SDK_ROOT/rtos/qurt/computev68/include/qurt \
		-isystem $HEXAGON_SDK_ROOT/ipc/fastrpc/rtld/ship/inc \
		-stdlib=libc++"

make runtime -j${nproc}

```

**Comment by aryamazaheri** [comment]
Many thanks, @abhikran-quic . I can now build tvm for hexagon. Maybe we should update the readme file in `src/runtime/hexagon/README.md` to contain these flags?

btw, there is still one issue with the compiled libtvm_runtime.so. When I import tvm on the target device, I get the following error:
`OSError: /data/tvm_build/hexagon/libtvm_runtime.so: wrong ELF class: ELFCLASS32`

My target hardware is a QRB5165M running an aarch64 Linux OS.

**Comment by abhikran-quic** [comment]
Sure @aryamazaheri . We have raised #14948 to fix this.

**Comment by aryamazaheri** [comment]
Great, many thanks
