### ISSUE TITLE
[TensorIR] Enhance PointerTypeRewrite

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#15463]
Our current GPU backends sometimes can generate the following code:

```c++
void kernel(float* global_data, float* res) {
    float data[4];
    ((float4*)data)[0] = ((float4*)global_data)[0];
     res[0] = data[0] + data[1] + data[2] + data[3];
}
```

Here we are doing vectorized store into a local memory then do a scalarized access from the local memory. While such pattern can be supported by compilers like cuda, it is not always the most robust path. Additionally, backends like vulkan, webgpu comes with the restriction that we can only have one kind of access to the data, resulting the code to be scalarized.

A better version of the code is as follows, when the following conditions are met:
- We detect we have aligned vector store into data
- For all read access to the data, they are scalar access, and can be represented by extract_element(Shuffle), this can be done by running modular analysis and check that all access have coeff that is multiple of the vector lane 

When such condition are met, we can still rewrite data into the vector type, and rewrite all read access of the data to extract_element(represented via shuffle).

```c++
void new_kernel(float4* global_data, float* res) {
    float4 vec_data[1];
    vec_data[0] = global_data[0];
    // access the elements of the vector.
    res[0] = vec_data[0].x + vec_data[0].y + vec_data[0].z + vec_data[0].w;
}
```

This is a pretty common case in GPU programs so it would be desirable to upgrade  `PointerTypeRewrite` to support such cases. This would likely help to robustify our overall support as the new_kernel is also what most programmer will write by handle 

## Action Items

- [ ] Enhance the var analysis to decouple buffer read and write/opaque access, 
     - The read part needs to contain a coeff entry via Modular analysis that summarizes whether rewrite to extract_element is possible
     - For all read access, do Modular analysis to get coeff, so we know that index = x * coeff + offset
     - If coeff % vector_lane == 0, then it means we can rewrite all scalar access to vector access `vec_data[(index - offset % veclane) // vec_lane].extract_element(offset % veclane)`. We can keep GCD of all coeff access to trigger the condition
     - To keep backward compatibility, we can put it behind a flag `rewrite_scalar_read_to_vector_shuffle` 
- [ ] Rewrite scalar read access into extract_element when we find such cases.
- [ ] Support extract_element shuffle pattern (more general shuffle pattern is OK but extract_element is the main one) in codegen , then turn `rewrite_scalar_read_to_vector_shuffle` on for the cases

cc @Hzfengsy @junrushao @quic-sanirudh @shingjan

**Comment by vinx13** [comment]
I'm interested in working on this

**Comment by Lunderberg** [comment]
I really like this idea, and it will simplify a lot of the codegen-time analysis that occurs to efficiently handle Ramp nodes.

Benefits:

* This mimics what is already done as part of the LLVM codegen ([link](https://github.com/apache/tvm/blob/main/src/target/llvm/codegen_llvm.cc#L1364)), in case of a
* This would remove the need for the `CodeGenC` generation of vector loads from Ramp indices([link](https://github.com/apache/tvm/blob/main/src/target/source/codegen_c.cc#L691)), since any vectorizable loads would already be expressed with scalar indices.  After the enhanced PointerTypeRewrite, `bool can_vector_load` would always be false in `CodeGenC::VisitExpr_(const BufferLoadNode*)`.
* The special handling that Vulkan has ([link](https://github.com/apache/tvm/blob/main/src/target/spirv/spirv_utils.cc#L123) could be removed entirely, since the lowered module would already satisfy the constraint `buffer_load.dtype == buffer_load.buffer.dtype`.

Potential breakages

* Vector types that whose struct representation contains padding.  For example, LLVM uses 32-bits to store `int8x3`, with padding in bits 24-31.  For these types, the address `((int8x3*)ptr)[N]` is not the same as `((int8*)ptr)[3*N]`.
* Padded vectorization of `AllocateConst`.  When a buffer's dtype is vectorized, the underlying data in `AllocateConst` is kept as-is.
* DLTensor arguments.  The size of a DLTensor is computed ([link](https://github.com/apache/tvm/blob/main/include/tvm/runtime/ndarray.h#L341)) assuming that elements are padded out to the nearest byte (e.g. padding a 1-bit `DataType::Bool()` out to 8 bits), but does not introduce any padding between vectorized elements (e.g. padding a 24-bit `DataType::Int(8, 3)` to 32 bits).

Likely follow-ups:

* Any remaining scalar read access would be updated from `((float*)ptr)[index]` to `extract_element(((float4*)ptr)[index/4], index%4)`, and the `((float4*)ptr)[index/4]` would likely benefit from CSE.  Currrently, the `tir.transform.CommonSubexprElimTIR` pass forbids removal of `BufferLoad` statements entirely ([link](https://github.com/apache/tvm/blob/main/src/tir/transforms/common_subexpr_elim.cc#L69)), as their contents may change.  We will probably want to loosen up this restriction, to allow CSE elimination of input buffers.
