### ISSUE TITLE
[RFC] Rust Support

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#1601]
There are two parts of the things that can be done in rust:
- Rust "frontend" as in java/js, that wraps the current C API and expose a rust programming model 
   - This allows most users to use tvm and its runtime(gpu/vulkan support etc)
   - Need to link runtime(by c++, or "backend" in next part)
- Rust "backend" which serves as an alternative to current C++ runtime.
   - It gives a standalone WASM module that even cpp does not yet offer(due to stdc++)
   - Security stuffs e.g. SGX

Both have values and I think we should have a good discussion on how can we organize them. 

- #1597 is mainly about "backend"
- @ehsanmok has implemented a version of "frontend"

cc @jroesch @nhynes @ehsanmok

**Comment by nhynes** [comment]
From an organizational perspective, we can have
```
tvm/rust/
    Cargo.toml  # a virtual manifest
    frontend/  # what @ehsanmok has been developing
        Cargo.toml
        src/
    runtime/  # what's currently in /tvm/rust/runtime
         Cargo.toml
```

the `runtime/` would continue to be the `tvm` package on crates.io and the frontend could be named elsewise.

**Comment by ehsanmok** [comment]
I agree @nhynes and I'd love to hear your feedbacks of my frontend when is completed as this is my first major Rust project and still learning a lot. The same to @jroesch as well :)

**Comment by tqchen** [comment]
Please also comment on official code-styles that we should generally follow in rust package

**Comment by nhynes** [comment]
> Please also comment on official code-styles that we should generally follow in rust package

The `.rustfmt.toml` currently used in #1597 is the default produced by `rustup --dump-config` for rustfmt version 0.6.1. We should just use the default unless there's a good reason not to.

**Comment by jroesch** [comment]
I would be happy to jump in and do some Rust hacking in the future with you guys, but am pretty busy with some new TVM stuff @tqchen and I have been working on. I'm happy to provide feedback and code review though, until I have a few more cycles available.

**Comment by tqchen** [comment]
rust runtime is merged in #1597

**Comment by tqchen** [comment]
Here are a few next steps:
- Add document generation to the ci flow
    - see https://github.com/dmlc/tvm/blob/master/tests/scripts/task_python_docs.sh#L10  which includes jsdoc and c++ docs
    - see results in https://docs.tvm.ai/api_links.html
- Add a README.md to rust with a few get started examples
- Rust fronend if @ehsanmok is interested in bring that in as well

**Comment by nhynes** [comment]
regarding docs, the conventional approach is to simply upload each release of the `tvm` crate to `crates.io` which will automatically build the docs and post them on `docs.rs`

**Comment by tqchen** [comment]
OK, we can do that then if that is the conventional approach for rust

**Comment by ehsanmok** [comment]
@tqchen Sorry, I was quite detached for some time and trying to finish it as soon as I can in my free time. I'm working on ergonimic registration of callbacks in Rust, when that's done I'd probably need help for the RPC as looking at the python and java RPC it's seems they have been sort of done from scratch!

**Comment by nhynes** [comment]
> RPC [...] seems they have been sort of done from scratch!

Now that we're on the topic, might it be a good time to start experimenting with a more established framework like [grpc](https://grpc.io/)? There's even a nice [crate](https://crates.io/crates/grpc) for it!

I may be completely incorrect in saying this, but I think that much of the roll-your-own components are a result of C++ having a terrible package ecosystem. For instance, [the dmlc-core json parser](https://github.com/dmlc/dmlc-core/blob/master/include/dmlc/json.h), [the memory stream reader](https://github.com/dmlc/dmlc-core/blob/master/include/dmlc/memory_io.h) used for params serdes, the [thread-local store](https://github.com/dmlc/dmlc-core/blob/master/include/dmlc/thread_local.h). In Rust, these become `serde`, `serde`, and `nom`, respectively. ezpz

**Comment by tqchen** [comment]
We roll out our own RPC because the requirement is somewhat different from grpc. We need a lightweight stateful session that persists over multiple function calls, it also helps porting into devices like android.

So there is a reason for rolling out the rpc module. I agree that json parser and thread local are somewhat unnecessary(thread_local is already supported in c++11 and it is there only for old compilers)

**Comment by ehsanmok** [comment]
@nhynes right! I already looked a little into [tarpc](https://github.com/google/tarpc) and [jsonrpc](https://github.com/paritytech/jsonrpc) to get some ideas. Given

>We need a lightweight stateful session that persists over multiple function calls

It is honestly beyond my knowledge and I need some time to understand the details so that I can see whether there's a Rust lib that we can leverage or should write our own. Do you know such a lib and what do you suggest?

@tqchen I like the most ideal case, but since 

> We want something that can interop (i.e. a good runtime system) and still enables writing pass in python, things might break in that land because of that ventures into a new territory

is a major requirement, maybe I'm wrong but I don't think using some promising Rust python bindings such as [pyo3](https://github.com/PyO3/pyo3) can handle that easily yet!

**Comment by nhynes** [comment]
Of `{tarpc, jsonrpc}`, I'd definitely go with _not_ jsonrpc. The reason jsonrpc exists is to serve web3 clients on the ethereum blockchain (which is what paritytech is all about). They don't necessarily care about this use case. `tarpc` doesn't look bad and might work with some `lazy_static!`s, but it also looks a bit more complicated than necessary. Whatever you'd find productive, I guess--as long as it's your rust lib on both ends; interop with existing TVM RPC is probably better, though.

> the most ideal case

rust-python programming isn't bad if there's a C repr. Unfortunately, that's the really hard part since it'd need _yet another_ IR, as the HalideIR is also C++.

The real issue I have with python-c++ is that even if the ops are written in C++, the schedules and patterns are still in python!

**Comment by tqchen** [comment]
I won't worry about the IR, but what we really want is a node system(like the one we had in tvm::Node), once we have that, we can always build an IR around

**Comment by ehsanmok** [comment]
Hopefully before the end of this week, I'll complete writing the docs and be ready for PR. In the meantime, you can checkout the [resnet example](https://github.com/ehsanmok/tvm-rust/tree/master/examples/resnet).

@nhynes I'd like to know in the proposed setup 
```
tvm/rust/
    Cargo.toml  # a virtual manifest
    frontend/ 
        Cargo.toml
        src/
    runtime/  # what's currently in /tvm/rust/
         Cargo.toml
        src/
    tvm-sys  # <-- Raw extern C API generated from bindgen
        Cargo.toml
        src/
```
shall we have a common, unified `tvm-sys` (matching the released version) with bindgen so that both runtime and frontend can import?

Also for the `.rustfmt.toml` I'd highly suggest to use the official and very common `tab_spaces = 4` instead of `tab_spaces = 2` for the whole rust repo.

**Comment by nhynes** [comment]
>  common, unified tvm-sys

Unfortunately, no because bindgen doesn't work when the target is exotic (e.g., wasm or sgx). That's why the headers are checked in as code. You're welcome to keep it as a top-level crate, though

Let's see how else your implementation looks, though. We might want a top-level `common/` crate for shared functionality.

> `tab_spaces = 4`

Two spaces is also common. At Google, 2 is used to make deeply nested code more readable. I'll defer to other community members here, but my strong preference is two spaces since it makes code more readable (esp. for rust where functional patterns encourage deep nesting). Again, let's see how your PR looks before we make a final decision. We should update (and stabilize on) rustfmt 1.0 at the same time, too.

**Comment by ehsanmok** [comment]
@tqchen @nhynes Frontend is finally [here](https://github.com/dmlc/tvm/pull/2291).

**Comment by ehsanmok** [comment]
@tqchen This can be closed now.
