### ISSUE TITLE
[Bug] CreateModulePass has an inconsistent para_format between BindSymbolicVars and other pass

### ISSUE THREAD

**Issue by Cookiee235** [apache/tvm#17225]
Hi all, I accidentally discovered that only the pass  `BindSymbolicVars ` has the prefix "relax.XX" when calling the function `CreateModulePass`, while all of the others have not. Is this a feature or a bug?  

I suspected that this would cause the function call to fail, so I opened this issue.

![image](https://github.com/user-attachments/assets/8878c75a-e4c3-4565-8b5c-004e609d72de)

cc @Lunderberg

**Comment by Lunderberg** [comment]
The names used for each pass are purely for human-readability, and aren't required to have any specific format.

By convention, passes that impacted Relay functions had no prefix, while passes that impacted TIR functions had a `"tir."` prefix.  Most of the Relax passes inherited the naming convention from Relay.  Unfortunately, this means that Relay and Relax transforms may have the same name (e.g. the name `"DeadCodeElimination"` is used both [here](https://github.com/apache/tvm/blob/main/src/relax/transform/dead_code_elimination.cc#L187) for Relax and [here](https://github.com/apache/tvm/blob/main/src/relay/transforms/dead_code.cc#L576) for Relay).

Since user scripts may specify per-pass config options by name (e.g. `with PassContext(disabled_pass=["some_pass_name"])`), updating the names to all have unique prefixes would break backwards compatibility.  It may be worth it at some point to avoid duplication, and to have an explicit IR type as part of every transform, but hasn't been a priority.

**Comment by Cookiee235** [comment]
@Lunderberg Thanks for your explanation. Sorry to report such a trivial issue. I closed it!

**Comment by Lunderberg** [comment]
No problem, and always happy to help!
