### ISSUE TITLE
README for Rust bindings says nightly is required

### ISSUE THREAD

**Issue by genbattle** [apache/tvm#7356]
The [README for the TVM rust bindings](https://github.com/apache/tvm/blob/main/rust/tvm/README.md) says that nightly rust is required, but I just downloaded, built and ran the tests for the bindings on stable Rust 1.49.0.

> This crate provides an idiomatic Rust API for TVM runtime frontend. Currently this requires *Nightly Rust* and tested on `rustc 1.32.0-nightly`

Is nightly Rust actually still required? If so, it may be helpful to list the features/dependencies that cause the nightly requirement as part of the README. If not, this requirement should be removed.

**Comment by jroesch** [comment]
Thanks for opening an issue! the current documentation needs to be rewritten I've been (slowly) working to refactor the bindings with a goal to have a stable version in the coming release. The Rust docs are more up to date, but in the repo docs are stale. This use to be true about the old bindings but CI uses a recent (1.47 last time I built the images) for CI.

**Comment by bkmgit** [comment]
Maybe this can be closed? Current [README](https://github.com/apache/tvm/blob/main/rust/tvm/README.md) indicates **stable rust**. This was updated in https://github.com/apache/tvm/commit/6aae48b3785aeba565138f4bb63884ae9930b2aa#diff-bba8fe6727b5adfdd8efe7eaaac3a5ac192c47910464500b046d9200701df4bd  Since Rust releases are frequent, maybe it is better to link to the Rust releases page than to give the current stable Rust version?

**Comment by bkmgit** [comment]
Pull request with suggested minor update https://github.com/apache/tvm/pull/13249
