### ISSUE TITLE
[CI] Fix Rust Docs Build

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#7744]
see https://github.com/apache/tvm/pull/7743

The recent outrages coulde due to multiple folds of reasons:

- The lack of environment variable updates as in task_rust.sh (LLVM_CONFIG_PATH) vs the task_python_docs
- Change of cargo behavior due to updates? (more likely below)
- The cargo might caches previous docs build if files does not change (the recent PR of Device refactor triggers a rebuild).

Possible steps:
- Fix the rust docs build script to make sure it always build correctly
- Consider some option like force rebuild that always rebuilds the docs(assuming not taking a lot time) regardless of caching

cc @Mousius @areusch @driazati @gigiblender

**Comment by binarybana** [comment]
I believe the key error was:
> error: couldn't read /workspace/rust/tvm-sys/src/c_runtime_api.rs: No such file or directory (os error 2)

And not the LLVM path because that `LLVM_CONFIG_PATH` warning shows up in previous successful runs.

`c_runtime_api.rs` is normally generated by [bindgen here](https://github.com/apache/tvm/blob/883954ee45b51ca8e2ff96714520a676cd1f8f74/rust/tvm-sys/build.rs#L79). So perhaps that got deleted and bindgen didn't get triggered as part of a semi-stale cache (so didn't trigger `build.rs`)? But I don't have time to dig deeper.

**Comment by tqchen** [comment]
cc @jroesch
