### ISSUE TITLE
[TIR][Bug] The buffer map, parameters and body do not agree on buffer variable identity. 

### ISSUE THREAD

**Issue by jroesch** [apache/tvm#7805]
Function parameters in TIR are incorrectly maintained when lowering. Even though there is no reason these should be different we don't maintain the variable identity between the function parameters, the buffer keys, buffer values and function body. 

```python
import tvm

output_shape = input_shape = (10, )
x = tvm.te.placeholder(input_shape, name="x")
y = tvm.te.placeholder(input_shape, name="y")
compute_output = tvm.te.compute(output_shape, lambda i: x[i] + y[i])
schedule = tvm.te.create_schedule([compute_output.op])
lowered = tvm.lower(schedule, [x, y, compute_output], simple_mode=False)
kernel = lowered["main"]
params = kernel.params
buffer_map_keys, buffer_map_values = zip(*kernel.buffer_map.items())
buffer_map_values = [buf.data for buf in buffer_map_values]

for p, k, v in zip(params, buffer_map_keys, buffer_map_values):
    print(f"param_match_key {p.same_as(k)}")
    print(f"value_match_key {k.same_as(v)}")
    print(f"param_match_value {p.same_as(v)}")

print(f"param_match_key {params[0].same_as(buffer_map_keys[0])}")
print(f"value_match_key {buffer_map_keys[0].same_as(buffer_map_values[0])}")
print(f"param_match_value {params[0].same_as(buffer_map_values[0])}")
print(f"params match in body {params[0].same_as(kernel.body.body.value.a.buffer_var)}")
print(f"key match in body {buffer_map_keys[0].same_as(kernel.body.body.value.a.buffer_var)}")
print(f"value match in body {buffer_map_values[0].same_as(kernel.body.body.value.a.buffer_var)}")
```

**Comment by jroesch** [comment]
cc @Hzfengsy @junrushao1994 @tqchen

**Comment by Hzfengsy** [comment]
It seems that `params` are always the same as `keys`, but unequal with `buffer.data`, while the `buffer.data` is used in the body. Right?

**Comment by junrushao1994** [comment]
Yeah it looks like the params in the PrimFunc signature are not the variables used in the function body.

```python
pf = lowered["main"]
# `addr1` is the variable in the function signature
addr1 = pf.params[0].handle
# `addr2` is the variable contained in the corresponding buffer
addr2 = pf.buffer_map[pf.params[0]].data.handle
# `addr3` is the variable used in the function body
addr3 = pf.body.body.value.a.buffer_var.handle

# we can see addr2==addr3, but addr1 != addr2
print(addr1)
print(addr2)
print(addr3)
```

Is this or a bug or intentional? like, to avoid cyclic dependency? @tqchen

**Comment by tqchen** [comment]
This is an expected behavior. See explaination of the buffer_map signature here https://github.com/apache/tvm/blob/main/include/tvm/tir/function.h#L57

Specifically, in the low level code, note there is a difference between the two things:
- The DLTensor* pointer that points to the DLTensor* structure
- The actual data pointer in the DLTensor structure that points to a data field.

The tvmscript format illustrates this fact more clearly

```python
@tvm.script.tir
def fun(a: ty.handle, b: ty.handle):
    Abuf = tir.match_buffer((3,), a, dtype="float32")
    Bbuf = tir.match_buffer((3,), b, dtype="float32")
    A_buffer_var: ty.Pointer("float32") = Abuf.data
    B_buffer_var: ty.Pointer("float32") = Bbuf.data
    B_buffer_var[0] = A_buffer_var[0] + 1
```
See also a C version that illustrate the type signature)
```c++
void func(DLTensor* a, DLTensor* b) {
    A_buffer_var = (float*)a.data;
    B_buffer_var = (float*)b.data;
    B_buffer_var[0] = A_buffer_var[0] + 1;
}
```

In the low level IR, the buffer vars corresponds to the data field(A_buffer_var and B_buffer_var). While the parameter arguments corresponds to the pointer to the DLTensor* field. Their relation are maintained via the match_buffer statements, and translates to the buffer_map field in the function signature.

This behavior is intended because it is important to distinguish the following three things in the IR:
- T0: in-memory pointer to the DLTensor*
- T1: abstract buffer(Abuf, Bbuf) that only exists during compile time, but will be staged to the individual elements
- T2: The pointer to the data field (A_buffer_var and B_buffer_var)

- T0 is needed because we need to faithfully represent the argument being passed to a function.
- T1 is needed, and cannot be T0 because in certainly cases like GPU, we cannot afford to pass a DLTensor* pointer directly to the kernel, but need to construct a buffer in an abstracted way, which get stagged to the individual fields
- T2 is needed because this is the data pointer that we directly operates on.

**Comment by tqchen** [comment]
Given this is more of a development question, we can also followup on the https://discuss.tvm.apache.org/
