### ISSUE TITLE
[Frontend][ONNX] No support for `RandomUniform` 

### ISSUE THREAD

**Issue by SamKG** [apache/tvm#8632]
This is mainly meant as a post for discussion purposes - trying to figure out how to best approach supporting this in the API.

Currently, there's no clear way to add support for the random operations.
ONNX relies on the existence of a global key (the op API doesn't specify any key); However, TVM doesn't seem to expose any such value.

Any feedback or advice on how to approach this would be appreciated.

**Comment by mbrookhart** [comment]
https://github.com/apache/tvm/blob/6d88bdd3ea36d9e3167eb92e167bd05f997c7fb3/python/tvm/relay/frontend/onnx.py#L3397-L3418

We have RandomUniform, but we haven't looked into the rest yet. There is a random number generator based on [ThreeFry Counter-based RNG](https://bashtage.github.io/randomgen/bit_generators/threefry.html), but it's probably not going to match the seed ONNX uses, so I would recommend testing some statistics on the output vs ONNX (mean, std, etc), rather than directly trying to get the same output. 

The threefry generator generates random bits if I remember correctly, you can see how uniform transforms that into a uniform distribution here: https://github.com/apache/tvm/blob/6d88bdd3ea36d9e3167eb92e167bd05f997c7fb3/python/tvm/topi/random/kernel.py#L483

**Comment by AndrewZhaoLuo** [comment]
https://github.com/apache/tvm/pull/8426 Has implemented this.

**Comment by AndrewZhaoLuo** [comment]
@SamKG is this issue able to be closed? I believe this is implemented now.
