### ISSUE TITLE
[Bug][VTA][OpenCL] If allowed to allocate in stack, VTA multiple target test will fail

### ISSUE THREAD

**Issue by zhanghaohit** [apache/tvm#8978]
In [`src/tir/transforms/lower_tvm_builtin.cc`](https://github.com/apache/tvm/blob/f6a404447406f91ddf6195ac044dc1f0b0e867e7/src/tir/transforms/lower_tvm_builtin.cc#L116):

```c++
    if (device_type_.defined()) {
      if (const auto* dev_type = device_type_.as<IntImmNode>()) {
        if (dev_type->value == kDLCPU) {
          int32_t constant_size = op->constant_allocation_size();
          if (constant_size > 0 && constant_size * nbytes < runtime::kMaxStackAlloca) {
            return stmt;
          }
        }
      }
    }
```

If the above optimization code is here, it will raise LLVM function signature errors when there are multiple targets. This piece of code was removed in #6126 to fix this issue. But it was reverted back in #8274, as removal of this code will cause some VM test failed.

To quick fix, the multiple target unittests are disabled in the current main branch. But we need further investigation on how to resolve this nicely.

cc @echuraev @elvin-n

**Comment by manupa-arm** [comment]
Thanks for flagging this!

IIUC,

This is problematic for micro because now the constant sized allocates are forced to be placed on stack (bypassing TVMPlatformAllocate abstraction) because that is how the codegen_c lowers the allocate.

https://github.com/apache/tvm/pull/8274#issuecomment-919102241

I dont think is desired.

Can someone explain why the guarded TVMBackendAllocWorkspace calls to allocate memory is problematic ? -- which are the ones I see generated in TIR prior to the last rever : #8274 ?

**Comment by manupa-arm** [comment]
Also for some reason, if we really need the tir.allocate to be translated down to as a stack placement, we should probably make the tir.allocate with storage_scope = "local" to PrimFunc that is placed on CPU.

keep the global ones served via TVMBAWs, because TVMBAW could serve as the 'global' allocator for memory.
In this way, in micro we could still use TVMBAWs to serve memory from the application/platform layer for 'global' allocates.

**Comment by mbrookhart** [comment]
FYI - this PR renables the test that this change breaks https://github.com/apache/tvm/pull/9019

**Comment by mbrookhart** [comment]
@mbs-octoml opened this issue to track an approach to better distinguish multiple targets https://github.com/apache/tvm/issues/9022
