### ISSUE TITLE
[Bug] [microTVM] [ProjectAPI] Error in TemplateProject generate_project_from_mlf

### ISSUE THREAD

**Issue by baibeta** [apache/tvm#9453]
### Expected behavior

generate_project_from_mlf should be work

### Actual behavior

TemplateProjectError received

### Environment

Ubuntu, latest tvm code base

### Steps to reproduce

-- python code:
```
temp_class_instance = tvm.micro.TemplateProject.from_directory(template_project_path)
my_temp_prj = temp_class_instance .generate_project_from_mlf(model_library_format_path, project_dir, project_options)
```
-- analysis:
In TemplateProject's __init__ :
```
        if not self._info["is_template"]:
            raise NotATemplateProjectError()
```
So is_template must be set to True.

But when calls TemplateProject's generate_project_from_mlf, it will call GeneratedProject.from_directory(project_dir, options).
And in GeneratedProject's __init__:
```
        if self._info["is_template"]:
           raise TemplateProjectError()
```
So TemplateProjectError is received. The code here seems to be illogical.

**Comment by leandron** [comment]
Hi @baibeta, can you post the full stack trace so that it is easier to see the same error as you see?

Also cc @areusch @gromero

**Comment by baibeta** [comment]
Traceback (most recent call last):
  File "/data/home/yifan.bai/code/tvm_latest/tvm/kws/my_prj.py", line 26, in <module>
    my_temp_prj  = temp_class_instance.generate_project_from_mlf(model_library_format_path, project_dir, project_options)
  File "/data/home/yifan.bai/code/tvm/python/tvm/micro/project.py", line 122, in generate_project_from_mlf
    return GeneratedProject.from_directory(project_dir, options)
  File "/data/home/yifan.bai/code/tvm/python/tvm/micro/project.py", line 68, in from_directory
    return cls(client.instantiate_from_dir(project_dir), options)
  File "/data/home/yifan.bai/code/tvm/python/tvm/micro/project.py", line 75, in __init__
    raise TemplateProjectError()
tvm.micro.project.TemplateProjectError

**Comment by areusch** [comment]
@baibeta could you post the `microtvm_api_server.py` you're using? in general this is intentional:
- it's expected that the user will supply a template project for use with microTVM
- TVM will always try to invoke generate_project with that template project, passing the MLF, and this function is expected to create a new project. it's expected that `microtvm_api_server.py` will copy itself into the new project.
- TVM will then close the connection to the `microtvm_api_server.py` and open a connection to the newly-copied `microtvm_api_server.py` in the generated project. 
- it's expected that this new copy has a way to detect that it was copied (e.g. you can also set a special file in the generated project, place the MLF tar in the generated project, or look for sources in the generated project which came from the MLF). 
- the new copy should then return is_template=false. 

let me know if this doesn't make sense. please feel free to re-open if there's an error here, happy to address any concern you may have.
