### ISSUE TITLE
[UX] Improve TensorIR jupyter misuse error message improvement suggestions

### ISSUE THREAD

**Issue by tqchen** [apache/tvm#9551]
Some lessons when trying out TensorIR on a jupyter session due to mis-use

- When passing different types(list of loops) to the split API, type checking error message is not as clear, consider do checking and raise error on python side.

https://gist.github.com/tqchen/01915c90334dbc2699971afe40dd2996

**Comment by junrushao1994** [comment]
UX issue should be treated as a bug

**Comment by junrushao1994** [comment]
The second issue is easier to fix: rewrite the error message.

The first issue is more profound: it comes from the type checking in packed function interface. One workaround is to check the input types on python side for each API. However I don't know better any general approaches to do so. On the other hand, if `get_loops` returns a list containing only one element, we can sugar it out; not sure if it's good design though because it sacrifices consistency

**Comment by junrushao1994** [comment]
Is it possible to turn off the stacktrace? It doesn't look useful in jupyter

**Comment by tqchen** [comment]
Let us check on the pythn side for the first one

**Comment by tqchen** [comment]
Updated note on the c++ stacktrace side. The main annoying part are the expanded macro dispatchers in the FFI boundary that does not provide additional information.

So one solution is to update the trace normalizer to simplify and skip some of the less informative traces(e.g. unpackcall_dispatcher) but keep the rest of the useful traces

**Comment by junrushao1994** [comment]
@tqchen The dispatcher can be completely avoided by using other metaprogramming tricks
